language: ruby
sudo: false
cache: bundler

matrix:
  include:
    - rvm: 2.3.8
      gemfile: Gemfile_4.2_legacy
    - rvm: 2.4.10
      gemfile: Gemfile_4.2
    - rvm: 2.4.10
      gemfile: Gemfile_5.2
    - rvm: 2.7.1
      gemfile: Gemfile_5.2_next
    - rvm: 2.7.1
      gemfile: Gemfile_6.1

notifications:
  email:
    - izikaj@gmail.com

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec
