source 'https://rubygems.org'

gem 'byebug'
gem 'dry-struct'
gem 'faker'
gem 'rails'
gem 'sqlite3'

group :test do
  gem 'guard', require: false
  gem 'guard-rspec', require: false
  gem 'rspec'
  gem 'rspec-rails'
end
